batch_size: 4              # How many independent sequences will we precess in parallel
block_size: 8              # What is the maximum context length for predictions
max_iters: 5000            # How many steps the model will be training for
eval_interval: 500         # Print out the loss every "eval_interval" steps
learning_rate: 0.001        # The model's learning rate
eval_iters: 200
embedding_dimensions: 32   # Represents the dimensionality of the feature vectors for each element in the input sequence
n_head: 4                   # Number of head in each block
n_layers: 3                 # Number of Blocks
dropout: 0.2